### PR TITLE
Fix WP Rocket SVG icon

### PR DESCRIPTION
**Pull request by mostafa-hisham**
@connorjclark in [Create WP Rocket PR](https://github.com/GoogleChrome/lighthouse-stack-packs/pull/88) you suggested [this change](https://github.com/GoogleChrome/lighthouse-stack-packs/pull/88#pullrequestreview-1225193574) to the SVG icon.

but now the logo is missing a part 
Stackpacks

and it should look like this
image

I reverted to the old icon and replaced `#` with `%23`

~~but the tests are failing and the SVG suggestion from it is removing the same part from the logo~~

~~What do we need to change to avoid this?~~

Uploaded SVG Logo without gradients to avoid svg test issue

### CODE REVIEW

**Comment by connorjclark** [comment]
If you want to keep the gradient, you should be able to by just copying the optimized SVG that the test failure prints out. Did you see that, or did it not work?

**Comment by mostafa-hisham** [comment]
@connorjclark i tried it but it didn't work
the gradient section was removed from the optimized svg

**Comment by connorjclark** [comment]
Ah, that is unexpected. Paste the SVG here and I'll add it back and change that test.

**Comment by mostafa-hisham** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 294 524"><defs><linearGradient id="a" x1="36.742%" x2="37.116%" y1="100.518%" y2="-.001%"><stop offset="0%" stop-color="%23DD5F29"/><stop offset="26.042%" stop-color="%23F26B32"/><stop offset="100%" stop-color="%23FAC932"/></linearGradient><linearGradient id="b" x1="28.046%" x2="28.421%" y1="100.518%" y2="-.003%"><stop offset="0%" stop-color="%23DD5F29"/><stop offset="26.042%" stop-color="%23F26B32"/><stop offset="100%" stop-color="%23FAC932"/></linearGradient><linearGradient id="c" x1="38.215%" x2="38.589%" y1="100.518%" y2="0%"><stop offset="0%" stop-color="%23DD5F29"/><stop offset="26.042%" stop-color="%23F26B32"/><stop offset="100%" stop-color="%23FAC932"/></linearGradient></defs><g fill="none" fill-rule="evenodd"><path fill="url(%23a)" d="M218.617 270.615c-9.752 0-18.896-5.689-23.366-14.63l-7.72-17.27h-76.6l-7.722 17.27c-4.47 8.941-13.613 14.63-23.366 14.63H75.78l32.712 249.306c1.625 4.671 4.673 4.671 6.502 0l32.51-79.648 28.242 79.442c1.625 4.676 4.673 4.676 6.501 0L220.04 270.82l-1.423-.204Z" transform="translate(-1.58 -.2)"/><path fill="url(%23b)" d="M184.47 231.784h-70.3l-10.77 24.179c-3.657 7.314-10.768 12.597-18.489 14.02L109.7 423.791c1.625 2.844 4.673 2.844 6.501 0l31.697-48.155 29.055 47.951c1.829 2.845 4.673 2.845 6.502 0l28.039-154.012c-6.908-2.032-13.004-6.908-16.255-13.613l-10.768-24.18Z" transform="translate(-1.58 -.2)"/><path fill="url(%23c)" d="m195.259 255.988-46.123-103.014-45.92 103.014c-1.625 3.048-3.656 5.69-6.095 7.925l19.1 102.2c1.015 1.423 3.657 1.83 5.485 0l25.601-33.931 25.602 33.728c1.625 2.032 4.47 1.626 5.485 0l21.131-103.42c-1.625-2.032-3.047-4.064-4.266-6.502Z" transform="translate(-1.58 -.2)"/><path fill="%23F56F46" d="M.439 12.559c-1.422-4.877 1.422-8.33 6.299-8.33H47.17c2.845 0 5.486 2.437 6.299 4.876l29.665 116.83h1.422l53.437-121.3c1.016-2.032 3.048-3.86 5.892-3.86h6.299c3.047 0 5.08 1.625 5.892 3.86l53.437 121.3h1.423L240.6 9.105c.61-2.439 3.454-4.877 6.299-4.877h40.433c4.877 0 7.518 3.454 6.299 8.33L228.41 244.188c-.61 2.845-3.454 4.876-6.298 4.876h-5.487c-2.438 0-4.876-1.625-5.892-3.86l-63.19-141.009h-1.015L83.744 245.203c-1.016 2.032-3.454 3.86-5.892 3.86h-5.486c-2.845 0-5.486-2.031-6.299-4.876L.44 12.559Z"/></g></svg>`

**Comment by mostafa-hisham** [comment]
@connorjclark 
We still have a problem with wp-rocket logo
here is a screenshot
image
as you can see the logo still missing a part it should look like this
Logo

**Comment by connorjclark** [comment]
There hasn't been a release with these changes yet - it'll be in the next one, though.

**Pull request closed without merging**
